# Generated by Django 5.2.16 on 2026-07-28 23:49

import apps.directory.models
import apps.directory.storages
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('abbreviation', models.CharField(blank=True, max_length=16)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_minors', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('identity', 'Photo ID'), ('registration', 'Regulator / professional body'), ('qualification', 'Qualification'), ('insurance', 'Professional indemnity insurance'), ('dbs', 'Enhanced DBS'), ('prescriber', 'Prescriber status'), ('ico', 'ICO registration')], max_length=20)),
                ('file', models.FileField(storage=apps.directory.storages.private_storage, upload_to=apps.directory.models.evidence_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('delete_after', models.DateTimeField(blank=True, help_text='Retention after listing removal. Period to be confirmed by the solicitor.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundingOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('group', models.CharField(choices=[('self_pay', 'Self-pay'), ('insurer', 'Insurer'), ('nhs', 'NHS'), ('employer', 'Employer')], max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['group', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('restricted', models.BooleanField(default=False, help_text='Protected or constrained title. Cannot publish without a VERIFIED registration with one of required_bodies.')),
                ('required_bodies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SessionFormat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('synonyms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, default=list, help_text='Feeds the search vector. Never displayed publicly.', size=None)),
                ('description', models.TextField(blank=True)),
                ('implies_minors', models.BooleanField(default=False, help_text='Implies work with under-18s. Contributes to the DBS requirement.')),
                ('seo_enabled', models.BooleanField(default=True, help_text='Eligible for /[speciality]/[town] landing pages.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'specialities',
                'ordering': ['category__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialityCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'speciality categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_log', to='directory.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('full_name', models.CharField(max_length=160)),
                ('display_title', models.CharField(blank=True, max_length=20)),
                ('post_nominals', models.CharField(blank=True, max_length=160)),
                ('pronouns', models.CharField(blank=True, max_length=40)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('non_binary', 'Non-binary'), ('undisclosed', 'Prefer not to say')], max_length=16)),
                ('headshot', models.ImageField(blank=True, upload_to='headshots/')),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('qualified_since', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('intro', models.TextField(blank=True, help_text='~100–150 words')),
                ('services', models.TextField(blank=True)),
                ('delivery_mode', models.CharField(choices=[('in_person', 'In person'), ('online', 'Online'), ('both', 'Both')], default='both', max_length=16)),
                ('offers_online', models.BooleanField(default=True)),
                ('online_coverage', models.CharField(blank=True, max_length=120)),
                ('is_prescriber', models.BooleanField(default=False)),
                ('offers_supervision', models.BooleanField(default=False)),
                ('public_email', models.EmailField(blank=True, max_length=254)),
                ('public_phone', models.CharField(blank=True, max_length=40)),
                ('public_website', models.URLField(blank=True)),
                ('booking_url', models.URLField(blank=True)),
                ('accepting_new_clients', models.BooleanField(default=True)),
                ('typical_wait', models.CharField(blank=True, choices=[('immediate', 'Within a week'), ('short', '1–2 weeks'), ('medium', '2–4 weeks'), ('long', '4+ weeks'), ('closed', 'Not accepting')], max_length=16)),
                ('evening_appointments', models.BooleanField(default=False)),
                ('weekend_appointments', models.BooleanField(default=False)),
                ('availability_note', models.CharField(blank=True, max_length=200)),
                ('fee_min', models.PositiveIntegerField(blank=True, null=True)),
                ('fee_max', models.PositiveIntegerField(blank=True, null=True)),
                ('free_initial_call', models.BooleanField(default=False)),
                ('offers_sliding_scale', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In review'), ('changes_requested', 'Changes requested'), ('approved', 'Approved'), ('published', 'Published'), ('suspended', 'Suspended'), ('unpublished', 'Unpublished (consent withdrawn)'), ('removed', 'Removed')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspend_reason', models.TextField(blank=True)),
                ('last_review_at', models.DateTimeField(blank=True, null=True)),
                ('completeness', models.PositiveSmallIntegerField(default=0)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('credentials_checked_at', models.DateTimeField(blank=True, help_text='Date shown on the badge: "Credentials checked 12 July 2026".', null=True)),
                ('verification_expires_at', models.DateTimeField(blank=True, help_text='Earliest expiry across required checks. Badge lapses here.', null=True)),
                ('minor_work_status', models.CharField(choices=[('n/a', 'No under-18 groups selected'), ('provisional', 'Provisional — adult work only, DBS pending'), ('cleared', 'Cleared — enhanced DBS verified'), ('blocked', 'Blocked — window elapsed, rejected or expired')], default='n/a', max_length=16)),
                ('provisional_expires_at', models.DateTimeField(blank=True, null=True)),
                ('provisional_extensions', models.PositiveSmallIntegerField(default=0, help_text='A second extension requires Dr. Abbass sign-off.')),
                ('plan_tier', models.CharField(default='free', max_length=16)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approaches', models.ManyToManyField(blank=True, related_name='practitioners', to='directory.approach')),
                ('client_groups', models.ManyToManyField(blank=True, related_name='practitioners', to='directory.clientgroup')),
                ('funding_options', models.ManyToManyField(blank=True, related_name='practitioners', to='directory.fundingoption')),
                ('languages', models.ManyToManyField(blank=True, related_name='practitioners', to='directory.language')),
                ('suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensions_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioner', to=settings.AUTH_USER_MODEL)),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='practitioners', to='directory.profession')),
                ('session_formats', models.ManyToManyField(blank=True, related_name='practitioners', to='directory.sessionformat')),
                ('specialities', models.ManyToManyField(blank=True, related_name='practitioners', to='directory.speciality')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='directory.practitioner'),
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('terms_version', models.CharField(max_length=40)),
                ('consent_publish', models.BooleanField()),
                ('consent_registered', models.BooleanField()),
                ('consent_independent', models.BooleanField()),
                ('consent_accurate', models.BooleanField()),
                ('consent_removal_path', models.BooleanField()),
                ('signed_name', models.CharField(max_length=160)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='directory.practitioner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='directory.practitioner')),
            ],
            options={
                'ordering': ['sort_order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='SlugRedirect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_slug', models.SlugField(max_length=140, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_redirects', to='directory.practitioner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='speciality',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialities', to='directory.specialitycategory'),
        ),
        migrations.CreateModel(
            name='TaxonomyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('axis', models.CharField(max_length=20)),
                ('proposed_term', models.CharField(max_length=120)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_requests', to='directory.practitioner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('identity', 'Photo ID'), ('registration', 'Regulator / professional body'), ('qualification', 'Qualification'), ('insurance', 'Professional indemnity insurance'), ('dbs', 'Enhanced DBS'), ('prescriber', 'Prescriber status'), ('ico', 'ICO registration')], max_length=20)),
                ('status', models.CharField(choices=[('not_submitted', 'Not submitted'), ('submitted', 'Submitted'), ('in_review', 'In review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='not_submitted', max_length=20)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Insurance and DBS expire. The badge lapses automatically with them.', null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('provisional_granted_at', models.DateTimeField(blank=True, null=True)),
                ('provisional_until', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks_made', to=settings.AUTH_USER_MODEL)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='directory.practitioner')),
                ('provisional_granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisionals_granted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='verification_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='directory.verificationcheck'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('entity_type', models.CharField(max_length=60)),
                ('entity_id', models.CharField(max_length=64)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='directory_a_entity__c1eab0_idx'), models.Index(fields=['created_at'], name='directory_a_created_4982c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('search_impressions', models.PositiveIntegerField(default=0)),
                ('profile_views', models.PositiveIntegerField(default=0)),
                ('email_reveals', models.PositiveIntegerField(default=0)),
                ('phone_reveals', models.PositiveIntegerField(default=0)),
                ('website_clicks', models.PositiveIntegerField(default=0)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='directory.practitioner')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='directory_d_date_290f88_idx')],
                'constraints': [models.UniqueConstraint(fields=('practitioner', 'date'), name='unique_metric_per_day')],
            },
        ),
        migrations.CreateModel(
            name='ConcernReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('inaccurate', 'Details are inaccurate'), ('not_registered', 'Registration concern'), ('misleading', 'Misleading claims'), ('other', 'Other')], max_length=20)),
                ('detail', models.TextField()),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='directory.practitioner')),
            ],
            options={
                'indexes': [models.Index(fields=['practitioner', 'handled_at'], name='directory_c_practit_ed4865_idx')],
            },
        ),
        migrations.CreateModel(
            name='PractitionerLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('address_line1', models.CharField(blank=True, max_length=160)),
                ('address_line2', models.CharField(blank=True, max_length=160)),
                ('city', models.CharField(max_length=80)),
                ('county', models.CharField(blank=True, max_length=80)),
                ('postcode', models.CharField(blank=True, max_length=12)),
                ('country_code', models.CharField(default='GB', max_length=2)),
                ('geo', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True, help_text='False = used for the search radius only; the address is not displayed.')),
                ('days_at_site', models.CharField(blank=True, max_length=80)),
                ('step_free_access', models.BooleanField(default=False)),
                ('wheelchair_access', models.BooleanField(default=False)),
                ('parking_available', models.BooleanField(default=False)),
                ('hearing_loop', models.BooleanField(default=False)),
                ('near_public_transport', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='directory.practitioner')),
            ],
            options={
                'ordering': ['-is_primary', 'city'],
                'indexes': [models.Index(fields=['city'], name='directory_p_city_3eead2_idx'), models.Index(fields=['postcode'], name='directory_p_postcod_363f59_idx')],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=40)),
                ('registration_no', models.CharField(max_length=40)),
                ('status', models.CharField(blank=True, max_length=60)),
                ('register_url', models.URLField(blank=True, help_text='Public register entry — used for the quarterly re-check.')),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='directory.practitioner')),
            ],
            options={
                'indexes': [models.Index(fields=['body', 'registration_no'], name='directory_r_body_657cdd_idx'), models.Index(fields=['last_checked_at'], name='directory_r_last_ch_3c2d49_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot', models.JSONField(help_text='What was submitted, so reviewers see exactly what they approved.')),
                ('changed_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None)),
                ('lint_flags', models.JSONField(blank=True, default=dict, help_text='POM names, efficacy claims, restricted titles, child-work terms.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('approved', 'Approved'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected')], max_length=20)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='directory.practitioner')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submitted_at'],
                'indexes': [models.Index(fields=['outcome', 'submitted_at'], name='directory_r_outcome_b2a30e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['status', 'is_verified'], name='directory_p_status_8f2db8_idx'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['status', 'accepting_new_clients'], name='directory_p_status_475e23_idx'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['status', 'minor_work_status'], name='directory_p_status_6f8217_idx'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['verification_expires_at'], name='directory_p_verific_32f0b6_idx'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['provisional_expires_at'], name='directory_p_provisi_8c273c_idx'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['featured_until'], name='directory_p_feature_f3801e_idx'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='directory_p_search__440af5_gin'),
        ),
        migrations.AddIndex(
            model_name='verificationcheck',
            index=models.Index(fields=['status', 'expires_at'], name='directory_v_status_fadf15_idx'),
        ),
        migrations.AddConstraint(
            model_name='verificationcheck',
            constraint=models.UniqueConstraint(fields=('practitioner', 'type'), name='unique_check_per_type'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['delete_after'], name='directory_d_delete__c706a0_idx'),
        ),
    ]
